name: Upstream Sync

permissions:
  contents: write
  actions: write

on:
  schedule:
    - cron: "0 0 * * *" # every day
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      # Step 1: checkout target repo
      - name: Checkout target repo
        uses: actions/checkout@v6

      # Step 2: check token
      - name: Check sync token
        run: |
          if [ -z "${{ secrets.UPDATESTREAM_SYNC_TOKEN }}" ]; then
            echo "UPDATESTREAM_SYNC_TOKEN is empty"
            exit 1
          else
            echo "UPDATESTREAM_SYNC_TOKEN exists"
          fi

      # Step 3: sync upstream changes
      - name: Sync upstream changes
        id: sync
        uses: aormsby/fork-sync-with-upstream-action@v3.4.3
        env:
          GH_TOKEN: ${{ secrets.UPDATESTREAM_SYNC_TOKEN }}
        with:
          upstream_sync_repo: fe-spark/EcoHub
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.UPDATESTREAM_SYNC_TOKEN }}

          test_mode: false

      # Step 4: sync check
      - name: Sync check
        if: failure()
        run: |
          echo "[Error] 由于上游仓库的 workflow 文件变更，导致 GitHub 自动暂停了本次自动更新"
          echo "[Error] Due to a change in the workflow file of the upstream repository"
          exit 1
